services:
  web:
    logging:
      options:
        max-size: 50m
    build:
      context: .
      target: development
    environment:
      NLS_LANG: "AMERICAN_AMERICA.WE8ISO8859P1"
    env_file:
      - '.env'
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:3001:3001
    volumes:
      - '.:/home/app'
    entrypoint: ["script/_entrypoint.sh"]
    command: >
      bash -c './script/_web_container_setup && ./script/_update_remote_database && ./script/_server'
