global_defaults: &global_defaults
  adapter: oracle

development:
  <<: *global_defaults
  username: <%= lookup('lastpass', 'asr_dev_user/development', field='username') %>
  password: <%= lookup('lastpass', 'asr_dev_user/development', field='password') %>
  host: <%= lookup('lastpass', 'asr_dev_user/development', field='Hostname') %>
  database: <%= lookup('lastpass', 'asr_dev_user/development', field='Database') %>
  
test:
  <<: *global_defaults
  username: <%= lookup('lastpass', 'asr_dev_user/test', field='username') %>
  password: <%= lookup('lastpass', 'asr_dev_user/test', field='password') %>
  host: <%= lookup('lastpass', 'asr_dev_user/test', field='Hostname') %>
  database: <%= lookup('lastpass', 'asr_dev_user/test', field='Database') %>
  
staging:
  <<: *global_defaults
  username: <%= lookup('lastpass', 'Shared-Applications/sessions/oracle_staging', field='username') %>
  password: <%= lookup('lastpass', 'Shared-Applications/sessions/oracle_staging', field='password') %>
  host: <%= lookup('lastpass', 'Shared-Applications/sessions/oracle_staging', field='Hostname') %>
  database: <%= lookup('lastpass', 'Shared-Applications/sessions/oracle_staging', field='Database') %>
  
production:
  <<: *global_defaults
  username: <%= lookup('lastpass', 'Shared-Applications/sessions/oracle_production', field='username') %>
  password: <%= lookup('lastpass', 'Shared-Applications/sessions/oracle_production', field='password') %>
  host: <%= lookup('lastpass', 'Shared-Applications/sessions/oracle_production', field='Hostname') %>
  database: <%= lookup('lastpass', 'Shared-Applications/sessions/oracle_production', field='Database') %>
