servers:
  web:
    hosts:
      - <%= ENV["WEB_HOST"] %>
    labels:
      traefik.http.routers.sessions-web.rule: Host(`sessions.umn.edu`) || Host(`sessions.prd.asr.umn.edu`)

env:
  clear:
    RAILS_ENV: "production"

logging:
  driver: journald
  options:
    tag: "sessions-web-production"
