servers:
  web:
    hosts:
      - asr-container-prd-web-public-01.oit.umn.edu
    labels:
      traefik.http.routers.sessions-web.rule: Host(`sessions.umn.edu`) || Host(`sessions.asr-container-prd-web-public-01.asr.umn.edu`)

env:
  clear:
    RAILS_ENV: "production"

logging:
  driver: journald
  options:
    tag: "sessions-web-production"
