servers:
  web:
    hosts:
      - asr-container-tst-web-public-01.oit.umn.edu
    labels:
      traefik.http.routers.sessions-web.rule: Host(`sessions-staging.umn.edu`) || Host(`sessions.asr-container-tst-web-public-01.asr.umn.edu`)

env:
  clear:
    RAILS_ENV: "staging"

logging:
  driver: journald
  options:
    tag: "sessions-web-staging"
