#!/bin/bash

set -e

cd "$(dirname "$0")/.."

if [ "$DRONE" = "true" ]
then
  echo "🤖 Drone only"
  echo "==> cleaning database"
  RAILS_ENV=test bin/rake oracle:clean
else
  echo "==> cleaning database"
  RAILS_ENV=development bin/rake oracle:clean
  RAILS_ENV=test bin/rake oracle:clean
fi
