#!/bin/bash

# script/_setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.
#               Intended to be run in the container.

# Put here any commands that need to be run on the container when running
#   setup.  For example: setting passwords
