#!/bin/sh

# script/_update_remote_database: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

script/_bootstrap

# clean and rebuild the database

script/_rebuild_database

echo "==> Database ready!"
