#!/bin/bash

# script/deploy: Tells Docker to run its deploy script

set -e

cd "$(dirname "$0")/.."

if [ $# -eq 0 ]; then
  echo "Provide a deploy target: script/deploy [production|staging]"
  exit 1
fi

echo "==> Deploying"

# populate the deployment environment variables
docker run \
  -it --rm \
  -e LASTPASS_USERNAME=$(whoami) \
  -v "$(pwd):/workdir" \
  asrcustomsolutions/lastpass:latest \
  ./script/_populate_env "$1"

# push the latest environment variables using Kamal
source "./script/_kamal"
kamal env push --destination="$1"

# deploy using Kamal
kamal deploy --destination="$1"
