#!/bin/bash

# script/setup: Tells Docker to setup the project by configuring YAML config files
# & getting and building Docker images.

set -e

cd "$(dirname "$0")/.."

echo "==> Pulling lastpass container"
docker pull asrcustomsolutions/lastpass:latest

echo "==> Running lpassify"
script/_lastpassify

echo "==> Checking architecture"
if [ `uname -m` = "arm64" ]; then
  echo "====> arm64 architecture detected"
  cp docker-compose.arm64.yml docker-compose.yml
else
  echo "====> x86 architecture detected"
  cp docker-compose.x86.yml docker-compose.yml
  cp config/database.docker.yml config/database.yml
fi

echo "ENV[\"STUB_INTERNET_ID\"] = \"$USER\"" > ./config/initializers/local.rb

echo "==> Getting/Building Docker images"
docker compose build --no-cache
docker compose pull

echo "==> Creating a pre-commit hook"
cp script/hooks/* .git/hooks

docker compose run --rm web script/_setup $(whoami)

echo "==> All done!"
