#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "*************************************************"
echo "While this app sets up, review the README.md file and update anything that's incorrect"
echo "https://github.umn.edu/asrweb/knowledgebucket/blob/master/best_practices/readmes.md"
echo "*************************************************"

echo "===> Getting passwords from LastPass if available"
[ -f ./bin/lastpassify ] && [ -f ./config/database.example.yml ] && ./bin/lastpassify
[ -f ./bin/lastpassify ] && [ -f ./config/secrets.example.yml ] && ./bin/lastpassify config/secrets.example.yml config/secrets.yml

echo "==> cleaning database"
RAILS_ENV=development bin/rake oracle:clean
RAILS_ENV=test bin/rake oracle:clean

if [ -z "$RAILS_ENV" ] && [ -z "$RACK_ENV" ]; then
  # Only things for a development environment will run inside here
  # Do things that need to be done to the application to set up for the first
  # time. Or things needed to be run to to reset the application back to first
  # use experience. These things are scoped to the application's domain.
  true
fi

echo "==> App is now ready to go!"
