#!/bin/bash

# script/test: Tells Docker to run the test suite. Run this one from your local machine

set -e

cd "$(dirname "$0")/.."

if [ "$(uname -s)" = "Linux" ]; then
  LINUX_DOCKER_SETTING=true
fi

if [ -n "$1" ]; then
  # pass arguments to test call. This is useful for calling a single test.
  docker compose exec -e LINUX_DOCKER=$LINUX_DOCKER_SETTING web script/_test "$1"
else
  docker compose exec -e LINUX_DOCKER=$LINUX_DOCKER_SETTING web script/_test
fi
