#!/bin/bash

# script/update: Tells Docker to run its update script

set -e

cd "$(dirname "$0")/.."

echo "==> Checking architecture"
if [ `uname -m` = "arm64" ]; then
  echo "====> arm64 architecture detected"
  docker compose exec -T web script/_update_remote_database
else
  echo "====> x86 architecture detected"
  docker compose exec -T web script/_update
fi

